spring:
  redis:
    host: ******
    password: ******
    database: 2
    pool:
#      池中"空闲"连接的最大数量
      max-idle: 8
#      池中在给定时间可以分配的最大连接数，负值表示无限制
      max-active: 8
#      连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（毫秒），负值表示无限期阻止
      max-wait: -1
#      池中的最小空闲连接数
      min-idle: 0
  application:
    name: redis-demo